use crate::{galaxy::{Location, LocationId},
          level::{LocationType, Tile},
          prefabs::{prefab, Prefab}};

pub const ID: LocationId = (2, 0, 0);

pub fn lava_prefab() -> Prefab {
  prefab(
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
arrrrrrrrrrrrrrrrrraaaaaaaaaaaaaaaaaaaaaaaaaaaaa
arllllllllllllllllraaaaaaaaaaaaaaaaaaaaaaaaaaaaa
arllllllllllllllllraaaaaaaaarraaaaaaaaaaaaaaaaaa
arllllllllllllllllrarraaaaaaaaaaaaaaaaaaaaaaaaaa
arllllrrrrllllllllraraaaaaaaaaarrrrrrrrrrrrrrrra
arllllrrrrllllllllraaaaaaaaaaaarllllllllllllllra
arllllrrrrllllllllraaaaaaaaaaaarllllllllllllllra
arllllrrrrllllllllraaaaaarraaaarllllllllllllllra
arllllrrrrllllllllraaaaaarraaaarllllllllllllllra
arllllllllllllllllraaaaaaaaaaaarllllllllllllllra
arllllllllllllllllraaaaaaaaaaaarllllllllllllllra
arllllllllllllllllraaaaaaaaaaaarllllllllllllllra
arllllllllllllllllraaaaaaaaaaaarllllllllllllllra
arrrrrrrrrrrrrrrrrraaaarraaaaaarllllllllllllllra
aaaaaaaaaaaaaaaaaaaaaaaraaaaaaarllllllllllllllra
aaaaaaaaaaaaaaaaaaaaaaaaaaaarrarllllllllllllllra
aaaaaraaaaaarraaaaaaaaaaaaaaraarllllllllllllllra
aaaaaraaaaaaaaaaaaaaaaaaaaaaaaarllllllllllllllra
aaaaaaaaaaarrrrrraaaaaaaaaaaarrrllllllccllllllrr
rraaaaaarrrccllllrrraaaaaarrrllrrrrrrrrrrrrrrrrl
llrrrrrrlllcclllllllrrrrrrllllllllllllrrrrrrllll
lllllllllllcclllllllllllllllllllllllllccllllllll
lllllllllllrrrrrrllllllllllllrrrrrrlllcclllllllr
rrllllllrrraaaaaarrrllllllrrraaaaaarrrccllllrrra
aarrrrrraaaaaaaaaaaarrrrrraaaaaaaaaaaarrrrrraaaa
aaaaaaaaaaaaaaaaaaaaaaaarraaaaaaaaaaaaaaaaaaaaaa
aarrrrrrrrrarraaaaaaaaaaaaaaaaaaaaaaaaarrrrrraaa
aarlllllllraraaaaaaaaaaaaaaaaaaaaaaaaaalllllraaa
aarlllllllraaarrrrrrrrraaaaaaaaaaaaPaaalllllraaa
aarlllllllraaarlllllllraaaaaaaaaaaaaaaalllllraaa
aarlllllllraaarlllllllraaaaaaaaaaaaaaaalllllraaa
aarlllllllraaarlllllllraaaaaaaaaaaarllllllllraaa
aarrrrrrrrraaarlllllllraaaaaaaaaaaarllllllllraaa
aaaaaaaaaaaaaarlllllllraaaaaaaaaaaarllllllllraaa
aaaaaaaaaaaaaarlllllllraaaaaaaaaaaarrrrrrrrrraaa
aaaaaaaaaaaaaarrrrrrrrraaaaaaaaaaaaaaaaaaaaaraaa
aaaaaaaaaaaaaaaaaaaaaaaaarrrrrrrrrrraarraaaaraaa
aaaaaaaaaaarraaaaaaaaaaaarllllllllraaaaaaaaaaaaa
arrrrrrrraaraaaaaaaaaaaaarllllllllraaaarrrrrrrrr
arllllllraaaaaaaaaaarraaarllllllllraaaarlllllllr
arllllllraaaaaaaaaaaaaaaarllllllllraaaarlllllllr
arllllllraaaaaaaaaaaaaaaarllllllllraaaarlllllllr
arllllllraaaaaaaaaaaaaaaarllllllllraaaarlllllllr
arllllllraaaaaaarraaaaaaarrrrrrrrrraaaarlllllllr
arllllllraaaaaaaaaaaaaaaaaaaraaaaaaaaaarlllllllr
arrrrrrrraaaaaaaaaaaaaaaaaaaaaaaaaaaaaarlllllllr
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarrrrrrrrr
")
    .assoc('a', (Tile::Ash, []))
    .assoc('l', (Tile::Lava, []))
    .assoc('r', (Tile::CaveWall, []))
    .assoc('c', (Tile::CaveFloor, []))
    .assoc('P', (Tile::ShipDock, []))
}

pub fn generate() -> Location {
  Location::from_prefab(
    lava_prefab(),
    LocationType::PlanetSurface { breathable: false },
    Tile::Ash
  )
}
